set -g mouse on
set -g history-limit 50000

setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R